// File generated by FlutterFire CLI & configured for DriftMind project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGP27vpPObuEzdEsfbLYYGM8mtSgJKbQQ',
    appId: '1:186245141458:web:9fa78c3adef81c9ed32e0b',
    messagingSenderId: '186245141458',
    projectId: 'driftmind-9ab16',
    authDomain: 'driftmind-9ab16.firebaseapp.com',
    storageBucket: 'driftmind-9ab16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGP27vpPObuEzdEsfbLYYGM8mtSgJKbQQ',
    appId: '1:186245141458:android:9fa78c3adef81c9ed32e0b',
    messagingSenderId: '186245141458',
    projectId: 'driftmind-9ab16',
    storageBucket: 'driftmind-9ab16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGP27vpPObuEzdEsfbLYYGM8mtSgJKbQQ',
    appId: '1:186245141458:ios:9fa78c3adef81c9ed32e0b',
    messagingSenderId: '186245141458',
    projectId: 'driftmind-9ab16',
    storageBucket: 'driftmind-9ab16.firebasestorage.app',
    iosBundleId: 'com.driftmind.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGP27vpPObuEzdEsfbLYYGM8mtSgJKbQQ',
    appId: '1:186245141458:ios:9fa78c3adef81c9ed32e0b',
    messagingSenderId: '186245141458',
    projectId: 'driftmind-9ab16',
    storageBucket: 'driftmind-9ab16.firebasestorage.app',
    iosBundleId: 'com.driftmind.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGP27vpPObuEzdEsfbLYYGM8mtSgJKbQQ',
    appId: '1:186245141458:web:9fa78c3adef81c9ed32e0b',
    messagingSenderId: '186245141458',
    projectId: 'driftmind-9ab16',
    authDomain: 'driftmind-9ab16.firebaseapp.com',
    storageBucket: 'driftmind-9ab16.firebasestorage.app',
  );
}
